[package]
name = "minimal_gui"
version = "0.1.0"
authors = ["pmosakowski <pmosakowski@users.noreply.github.com>"]

[dependencies]
conrod = { version = "*", features = ["glium", "winit"] }
find_folder = "*"
rand = "*"
